import { TBook } from '../model/book.model';

export const dummyBooks: TBook[] = [
  {
    id: 5,
    title: 'Dummy Book',
    img: 7,
    category_id: 3,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail:
      'Dummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy DetailDummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 1,
    title: 'Dummy Book',
    img: 5,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 2,
    title: 'Dummy Book',
    img: 4,
    category_id: 2,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 3,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 3,
    title: 'Dummy Book',
    img: 2,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 4,
    title: 'Dummy Book',
    img: 5,
    category_id: 2,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 6,
    title: 'Dummy Book',
    img: 11,
    category_id: 3,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
  {
    id: 7,
    title: 'Dummy Book',
    img: 15,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 8,
    title: 'Dummy Book',
    img: 9,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 9,
    title: 'Dummy Book',
    img: 2,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 10,
    title: 'Dummy Book',
    img: 20,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 11,
    title: 'Dummy Book',
    img: 21,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 12,
    title: 'Dummy Book',
    img: 22,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 13,
    title: 'Dummy Book',
    img: 23,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 14,
    title: 'Dummy Book',
    img: 25,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 15,
    title: 'Dummy Book',
    img: 26,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 16,
    title: 'Dummy Book',
    img: 27,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },

  {
    id: 17,
    title: 'Dummy Book',
    img: 28,
    category_id: 1,
    summary: 'Dummy Summary',
    author: 'Dummy Author',
    price: 10000,
    likes: 1,
    form: 'paperback',
    isbn: 'Dummy ISBN',
    detail: 'Dummy Detail',
    pages: 100,
    contents: 'Dummy Contents',
    pubDate: '2021-01-01',
  },
];
